### ISSUE TITLE
Styling/CSS to be upgraded

### ISSUE THREAD

**Issue by oIdioN** [frankrl86/FEBC_Project01#33]
Font/styling needs to be cinsistent throughout the pages

**Comment by KaleimS** [comment]
I changed the font in the recipes HTML to match the index.html it is now Poppins

**Comment by KaleimS** [comment]
Also added the new footer and header in recipes HTML to match the other pages

**Comment by KaleimS** [comment]
Lastly i changed the color of the cards on the recipes HTML to match more with the color scheme for the website

**Comment by oIdioN** [comment]
Recipe footer fixed. JS called twice why? 2nd will be taken off
